# -*- coding: utf-8 -*-
"""Linear Regression Using Tensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xD_GWuPbj0SRcXxKzlduIlvvxDiV2IH1
"""

!pip install tensorflow

"""Talking to computer:

“Make sure TensorFlow library exists in memory.”
"""

import tensorflow as tf

"""Talking to computer:

“Load TensorFlow tools so I can use tensors, variables, and gradients.”

Computer response:
TensorFlow engine loaded.
"""

X = tf.constant([1., 2., 3., 4., 5.])
Y = tf.constant([5., 8., 11., 14., 17.])

"""Talking to computer:

“Create input tensor X.”
“Create output tensor Y.”
"""

W = tf.Variable(0.0)
b = tf.Variable(0.0)

"""Talking to computer:

“Create weight W.”
“Create bias b.”
“Both start at 0.”
“They must be changeable.”

Computer creates memory slots:

W = 0
b = 0

These will learn.
"""

learning_rate = 0.01

"""Talking to computer:

“When updating weights, don’t move too much.”
“Take small steps.”
"""

for epoch in range(1000):
    with tf.GradientTape() as tape:
        predictions = W * X + b
        loss = tf.reduce_mean((predictions - Y) ** 2)

    grad_W, grad_b = tape.gradient(loss, [W, b])

    W.assign_sub(learning_rate * grad_W)
    b.assign_sub(learning_rate * grad_b)

print("Final W:", W.numpy())
print("Final b:", b.numpy())